# Training database connection template

#driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#url=jdbc:log4jdbc:mariadb://127.0.0.1:3306/training
#username=training_user
#password=training_password


driver=org.mariadb.jdbc.Driver
url=jdbc:mariadb://127.0.0.1:3306/WRM
username=APP
password=APP